---
# tasks file for postgres

# - name: Show ansible_distribution_major_version
#   ansible.builtin.debug:
#     var: ansible_distribution_major_version
#   run_once: true
#   delegate_to: localhost

# - name: Show _postgres_version
#   ansible.builtin.debug:
#     var: _postgres_version[ansible_os_family][ansible_distribution_major_version]
#   run_once: true
#   delegate_to: localhost

# - name: Show postgres_install_version
#   ansible.builtin.debug:
#     var: postgres_install_version
#   run_once: true
#   delegate_to: localhost

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Enable postgres module
  ansible.builtin.dnf:
    name: "@postgresql:{{ postgres_install_version }}/server"
    state: present
  # notify:
  #   - Systemctl daemon-reexec
  when:
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version | int > 7 and
    postgres_install_version | int != postgres_version | int

- name: Install postgres
  ansible.builtin.package:
    name: "{{ postgres_packages }}"
    state: present
  notify:
    - Systemctl daemon-reexec

- name: Create postgres data directory
  ansible.builtin.file:
    path: "{{ postgres_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: "700"

- name: Initialize database
  ansible.builtin.command:
    cmd: initdb -D {{ postgres_dir }}
    creates: "{{ postgres_dir }}/PG_VERSION"
  when:
    - ansible_os_family != "Debian"
  become_user: postgres
  become: true

- name: Configure postgres
  ansible.builtin.lineinfile:
    path: "{{ postgres_conf_dir }}/postgresql.conf"
    regex: "^{{ item.value.name | default(item.key) }} ="
    line: "{{ item.value.name | default(item.key) }} = {{ item.value.value | default(item.value) }}"
    create: true
    mode: "0644"
  notify:
    - Restart postgres
  loop: "{{ postgres_config_entries | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.value.name | default(item.key) }}"

- name: Create pg_hba.conf
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_conf_dir }}/pg_hba.conf"
    backup: true
    mode: "0644"
  notify:
    - Reload postgres

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start and enable postgres
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: Install python3-psycopg2
  ansible.builtin.package:
    name: python3-psycopg2
    state: present
  when:
    - postgres_databases is defined or
      postgres_users is defined
    - ansible_os_family == "RedHat"

# - name: Install psycopg2-binary
#   ansible.builtin.pip:
#     name: psycopg2-binary
#     state: present
#   when:
#     - postgres_databases is defined or
#       postgres_users is defined
#     - ansible_os_family != "Debian"

- name: Flush handlers again
  ansible.builtin.meta: flush_handlers

- name: Create postgres database
  community.postgresql.postgresql_db:
    db: "{{ item.name }}"
    encoding: "{{ item.encoding | default(omit) }}"
    conn_limit: "{{ item.conn_limit | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    trust_input: "{{ item.trust_input | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    port: "{{ postgres_port }}"
  loop: "{{ postgres_databases }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - postgres_databases is defined
  become_user: postgres
  become: true

- name: Create postgres users
  community.postgresql.postgresql_user:
    user: "{{ item.name }}"
    db: "{{ item.db | default(omit) }}"
    password: "{{ item.password }}"
    expires: "{{ item.expires | default(omit) }}"
    port: "{{ postgres_port }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
  loop: "{{ postgres_users }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - postgres_users is defined
  become_user: postgres
  become: true
  no_log: true
